
@echo off

REM !!! Generated by the fmp-cli 1.85.0.  DO NOT EDIT!

md LayoutMenu\Assets\3rd\fmp-xtc-layoutmenu

cd ..\vs2022
dotnet build -c Release

copy fmp-xtc-layoutmenu-lib-mvcs\bin\Release\netstandard2.1\*.dll ..\unity2021\LayoutMenu\Assets\3rd\fmp-xtc-layoutmenu\
